apiVersion: apps/v1
kind: Deployment
metadata:
  name: cylbing
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cylbing
  template:
    metadata:
      labels:
        name: cylbing
    spec:
      restartPolicy: Always
      containers:
        - name: cylbing
          image: chunyanlee/cylbing
          ports:
            - containerPort: 3000
            
---
apiVersion: v1
kind: Service
metadata:
  name: cylv3kurl
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "cylbing"
    port: 3000
  selector:
    name: cylbing
