apiVersion: apps/v1
kind: Deployment
metadata:
  name: cylv4
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cylv4
  template:
    metadata:
      labels:
        name: cylv4
    spec:
      restartPolicy: Always
      containers:
        - name: cylv4ku
          image: chunyanlee/cylv3
          ports:
            - containerPort: 3000
            
---
apiVersion: v1
kind: Service
metadata:
  name: cylv4kurl
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "cylv4kurl"
    port: 3000
  selector:
    name: cylv4
